#file: noinspection YAMLSchemaValidation
version: '3.8'

networks:
  integration-test-example:

services:
  it_test:
    image: amazoncorretto:17.0.9-alpine3.18
    volumes:
      - $PWD:/app
    working_dir: /app
    depends_on:
      - db
    networks:
      - integration-test-example
    command: ["sh", "-c", "dos2unix ./gradlew","./gradlew","clean","controllerTest"]
  db:
    image: postgres:16.0
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: posttest
    restart: on-failure
    volumes:
      - ./db:/docker-entrypoint-initdb.d/
    networks:
      - integration-test-example