version: '3.8'

networks:
  integration-test-example:

services:
  db:
    image: postgres:16.0
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: posttest
    restart: on-failure
    ports:
      - "5432:5432"
    volumes:
      - ./db:/docker-entrypoint-initdb.d/
    networks:
      - integration-test-example